name: Docker Build (pull-request)
on:
  pull_request:
    branches:
      - main
    paths:
      - 'docker/**/*'

permissions:
  id-token: write
  contents: read

jobs:
  docker:
    name: Build Docker
    uses: smg-real-estate/.github/.github/workflows/aws_ecr.yml@main
    with:
      push: false
      # specify the path to Dockerfile
      image_path: docker/mlflow
      # specify the image name in ECR
      image_name: mlflow
    secrets:
      # IAM role to access ECR
      DEPLOYER_ARN: ${{ secrets.HG_DATASERVICES_TEST_DEPLOYER_ARN }}
