name: Deploys AWS CF stacks using CDK

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_options:
        required: false
        type: string
      env:
        required: false
        type: string
    secrets:
      DEPLOYER_ARN:
        required: true
env:
  PRE_COMMIT_HOME: /tmp/.cache/pre-commit

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.image_name }}
      options: ${{ inputs.image_options }}
    environment:
      name: ${{ inputs.env }}
      url: ${{ steps.cdk-deploy.outputs.api_url }}
    env:
      ENVIRONMENT: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v3
      - uses: smg-real-estate/.github/.github/actions/poetry-dependencies/@v1
      - uses: aws-actions/configure-aws-credentials@v1
        id: aws-login
        with:
          aws-region: eu-central-1
          role-to-assume: ${{ secrets.DEPLOYER_ARN }}
          role-duration-seconds: 3600
          role-skip-session-tagging: true
# uncomment if bootstrap is needed
#     - run: poetry run cdk bootstrap aws://${{ steps.aws-login.outputs.aws-account-id }}/eu-central-1
      - id: cdk-deploy
        run: |
          poetry run cdk deploy --require-approval=never --all --outputs-file ./cdk-outputs.json
          endpoint_url=$(jq -r ".[\"$(jq -r '.| keys[0]' ./cdk-outputs.json)\"].ApiEndpoint" ./cdk-outputs.json)
          echo "::set-output name=api_url::$endpoint_url"
