
name: Get Model version 
on:
  workflow_call:
    inputs:
      service_url:
        required: false
        type: string
      new_version:
        required: false
        type: string
    outputs:
      model_version:
        description: "Model version in production system"
        value: ${{ jobs.get_model_version.outputs.model_version }}

jobs:
  get_model_version:
    runs-on: ubuntu-latest
    outputs:
      model_version: ${{ steps.set-model-version.outputs.model_version }}
    steps:
      - id: set-model-version
        if: '! inputs.new_version'
        run: echo "::set-output name=model_version::2022-07-18/"
      - id: set-model-version
        if: inputs.new_version
        run: echo "::set-output name=model_version::${{ inputs.new_version }}"
